name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/projects/NGO-PLATFORM
            git fetch origin main
            git reset --hard origin/main

            cd ngo-project

            export JAVA_HOME=$(dirname $(dirname $(readlink -f $(which java))))
            export PATH=$JAVA_HOME/bin:$PATH

            echo "JAVA VERSION:"
            java -version

            echo "MAVEN VERSION:"
            mvn -version

            mvn clean package -DskipTests

            pkill -f 'ngo-project.*\.jar' || true
            nohup java -jar target/ngo-project-1.0.0.jar > /home/ec2-user/app.log 2>&1 &

            cd ../ngo-frontend
            npm install
            npm run build